FROM node:20-alpine

WORKDIR /app

# Copier les fichiers package
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste des fichiers
COPY . .

# Exposer le port
EXPOSE 3000

# Commande par défaut (overridée par docker-compose)
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
